// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsZAwdbNmiO69-7Vx5ecaYcykCCiG0ImM',
    appId: '1:399857772683:web:ee7aed0a07975c0c100c8e',
    messagingSenderId: '399857772683',
    projectId: 'chatapp-d6d57',
    authDomain: 'chatapp-d6d57.firebaseapp.com',
    storageBucket: 'chatapp-d6d57.appspot.com',
    measurementId: 'G-SDQVJQMV5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpOznEIpvOynl2HgSollt6SDYCX-0nc1w',
    appId: '1:399857772683:android:db0e30487f9f9388100c8e',
    messagingSenderId: '399857772683',
    projectId: 'chatapp-d6d57',
    storageBucket: 'chatapp-d6d57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbFDr03ppVEH19rfU1m2kS9AEOr7MpKJo',
    appId: '1:399857772683:ios:2df2032b62f28f24100c8e',
    messagingSenderId: '399857772683',
    projectId: 'chatapp-d6d57',
    storageBucket: 'chatapp-d6d57.appspot.com',
    iosClientId: '399857772683-k8bt4o9777hi2t5a79pbaat876tsvia1.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
